### ISSUE TITLE
the readme is not enough.

### ISSUE THREAD

**Issue by meansoup** [oracle-actions/configure-kubectl-oke#12]
can you explain more how can I deploy by this actions?
I want to use this, but I couldn't make it works.

I just added secrets what you mentioned in readme, but it keeps pending. 

this is my action yml.
- https://github.com/meansoup/whatisthebetter/blob/main/.github/workflows/oke-deploy.yml

**Comment by Djelibeybi** [comment]
If the Action never actually starts, that's a GitHub issue, not a problem with the action itself. 

You can see my test action here: https://github.com/Djelibeybi/oracle-actions-testing/blob/main/.github/workflows/configure-kubectl-for-oke.yml and the output of that is here: https://github.com/Djelibeybi/oracle-actions-testing/runs/7995202618?check_suite_focus=true

The only other thing to ensure is that your OKE cluster has a publicly accessible API endpoint so the GitHub Action runner can connect to it.

**Comment by meansoup** [comment]
it works if I change `runs-on: ubuntu` as `runs-on: ubuntu-latest`.
thank you.

**Comment by Djelibeybi** [comment]
Ah, interesting. Thanks for letting me know!
