### ISSUE TITLE
kubectl not executable

### ISSUE THREAD

**Issue by tonybolzan** [oracle-actions/configure-kubectl-oke#19]
Executable bit is not active for kubectl binary. Change `0o644` to `0o755`
This give a error `Permission denied`

https://github.com/oracle-actions/configure-kubectl-oke/blob/main/src/main.ts#L32

**Comment by Djelibeybi** [comment]
Ok, so that's weird: the action is tested by running `kubectl` so it must work and yet this is clearly an issue. Are you able to submit a PR to fix?

**Comment by tonybolzan** [comment]
Github Runner `ubuntu-latest` has Kubectl 1.25.3 instaled by default
- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#tools

I will make a PR tomorrow

**Comment by Djelibeybi** [comment]
Thanks! I would only have time to look at this next week, so much appreciated
