### ISSUE TITLE
explicit endpoint

### ISSUE THREAD

**Issue by rajashekhargundeti** [oracle-actions/configure-kubectl-oke#24]
Hi

How to connect to an explicit endpoint pointing to a different service endpoint? 

--endpoint https://containerengine-XXX.us-ashburn-1.oci.oraclecloud.com

oci ce cluster create-kubeconfig --cluster-id ocid1.clusterinteg.oc1.iad.XXX --file $HOME/.kube/config --region us-ashburn-1 --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT --profile xyz --auth security_token --endpoint https://containerengine-XXX.us-ashburn-1.oci.oraclecloud.com

**Comment by Djelibeybi** [comment]
Why would you need to do that? Just provide the Cluster OCID and the action will determine the endpoint URL itself.
