### ISSUE TITLE
ARM64 support for kubectl

### ISSUE THREAD

**Issue by galovics** [oracle-actions/configure-kubectl-oke#28]
Currently the architecture is hardcoded in the download URL for kubectl at https://github.com/oracle-actions/configure-kubectl-oke/blob/main/src/main.ts#L27

An extra parameter could be added to configure the target architecture, defaulting to amd64 to not break any existing usage of the action.

**Comment by Djelibeybi** [comment]
Good suggestion, thanks.

**Comment by Djelibeybi** [comment]
I guess it would be better to populate this based on the architecture of the runner on which the action is currently running as opposed to requiring the user to configure it correctly.

**Comment by galovics** [comment]
@Djelibeybi agreed. I was just thinking of the configuration (after spending a good amount of time) to make this as easy to implement as possible.

In the meantime, I came across the setup-helm action as well and I saw those guys have implemented it. Probably copying it would be the easiest.

https://github.com/Azure/setup-helm/blob/main/src/run.ts#L110

**Comment by galovics** [comment]
@Djelibeybi had some spare time, did a PR, pls take a look: https://github.com/oracle-actions/configure-kubectl-oke/pull/31

**Comment by Djelibeybi** [comment]
Closed via #35
