### ISSUE TITLE
Error Encountered When Installing OCI CLI in GitHub Actions: "Externally Managed Environment"

### ISSUE THREAD

**Issue by GuilhermeFaga** [oracle-actions/configure-kubectl-oke#70]
We're experiencing an issue in multiple repositories where the GitHub Actions workflow fails during the installation of the Oracle Cloud Infrastructure (OCI) CLI. The error message indicates that the Python environment is managed externally, preventing the installation of the OCI CLI package via pip.

```bash
Run oracle-actions/configure-kubectl-oke@v1.5.0
  
Installing Oracle Cloud Infrastructure CLI
  /usr/bin/python -m pip install oci-cli
  error: externally-managed-environment
  × This environment is externally managed
  ╰─> To install Python packages system-wide, try apt install
      python3-xyz, where xyz is the package you are trying to
      install.
      
      If you wish to install a non-Debian-packaged Python package,
      create a virtual environment using python3 -m venv path/to/venv.
      Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
      sure you have python3-full installed.
      
      If you wish to install a non-Debian packaged Python application,
      it may be easiest to use pipx install xyz, which will manage a
      virtual environment for you. Make sure you have pipx installed.
      
      See /usr/share/doc/python3.12/README.venv for more information.
  note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
  hint: See PEP 668 for the detailed specification.
  Error: The process '/usr/bin/python' failed with exit code 1
```

**Comment by viniciusczar** [comment]
I'm having the same problem here

**Comment by Djelibeybi** [comment]
Looks like something on the GitHub Runners is now preventing the installation of additional Python modules. I'll check to see if this is a known issue.

**Comment by Djelibeybi** [comment]
Upstream issue: https://github.com/actions/runner-images/issues/10781

**Comment by Djelibeybi** [comment]
Looks like the workaround (for now) is to add `setup-python` step before the `configure-kubectl-oke` action. Though I suggest monitoring the upstream thread for its resolution as well.

**Comment by GuilhermeFaga** [comment]
@Djelibeybi @viniciusczar other workaround for this issue is setting the ubuntu version to `ubuntu-22.04`. Thanks for finding the upstream issue, really helped!
